# Template for setting up the python environment (with optional pinned requirements)
# and running all tests (except for install tests)

# Some key parameters:

# platform
# A human-readable string which should be set to match vmImage

# testRunType: {Unit, Notebooks}
# Specifies the set of tests to be run

# installationType: {None, PipLocal, PyPI}
# Specifies how Fairlearn should be made available. Note
# that the Notebooks tests will not work with 'None'
# If PyPI is specified, then targetType, versionArtifactName
# and versionArtifactFile need to be specified, in order to
# determine which PyPI archive to use, and which version
# of Fairlearn to fetch from it.

parameters:
  platforms: { Linux: ubuntu-latest, Windows: vs2017-win2016 }
  testRunTypes: ['Unit', 'Notebooks']
  installationType: ''
  pyVersions: [3.5, 3.6, 3.7, 3.8]
  pinRequirements: False
  freezeArtifactStem: 
  freezeFileStem:
  # Following are used if the installationType is PyPI
  targetType: 'Test'
  versionArtifactName:
  versionArtifactFile:

jobs:
  - ${{ each p in parameters.platforms }}:
    - ${{ each trt in parameters.testRunTypes }}:
      - ${{ each pyVer in parameters.pyVersions }}:
        - job:
          displayName: ${{ format('{0} {1} {2}', p.Key , trt, pyVer) }}
          pool:
            vmImage: ${{ p.value }}

          variables:
              ${{ if eq(parameters.targetType, 'Test') }}:
                pypiUrl: https://test.pypi.org/simple/
              ${{ if eq(parameters.targetType, 'Prod') }}:
                pypiUrl: https://pypi.org/simple/
              RequirementsFile: requirements-${{pyVer}}.txt
              FreezeArtifact: '${{parameters.freezeArtifactStem}}${{p.Key}}${{trt}}${{pyVer}}'
              FreezeFile: '${{parameters.freezeFileStem}}-${{p.Key}}${{trt}}${{pyVer}}.txt'

          steps:
          - template: test-run-step-template.yml
            parameters:
              testRunType: ${{trt}}
              installationType: ${{parameters.installationType}}
              pythonVersion: ${{pyVer}}
              pinRequirements: ${{parameters.pinRequirements}}
              requirementsFile: $(RequirementsFile)
              freezeArtifact: $(FreezeArtifact)
              freezeFile: $(FreezeFile)
              # Following are used if the installationType is PyPI
              pypiUrl: $(pypiUrl)
              versionArtifactName: ${{parameters.versionArtifactName}}
              versionArtifactFile: ${{parameters.versionArtifactFile}}